---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://wendal.net

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
  
paginator:
  namespace: "/posts/"
  per_page: 10
  root_page: "/"
  layout: "paginator"
